"""empty message

Revision ID: 3566114bdab1
Revises: d28e03031e7e
Create Date: 2025-04-22 18:21:04.830659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3566114bdab1'
down_revision = 'd28e03031e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('likes_post_id_fkey', type_='foreignkey')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'likes', ['like_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('like_id')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('likes_post_id_fkey', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###
