"""empty message

Revision ID: 812eb50ca6e6
Revises: 67ed5a40d6f7
Create Date: 2025-04-22 15:42:03.697648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812eb50ca6e6'
down_revision = '67ed5a40d6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peapole')
    op.drop_table('planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('planet_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('climate', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planet_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('peapole',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('homeworld_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['homeworld_id'], ['planet.id'], name='peapole_homeworld_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='peapole_pkey')
    )
    # ### end Alembic commands ###
