"""empty message

Revision ID: 8ad62be11dd7
Revises: 3566114bdab1
Create Date: 2025-04-22 18:22:29.877552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad62be11dd7'
down_revision = '3566114bdab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'likes', ['like_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('like_id')

    # ### end Alembic commands ###
